version: '3'
services:
  backend:
    image: 424690321854.dkr.ecr.us-west-2.amazonaws.com/myinsn-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - '3000:3000'
    labels:
      aws.ecs.fargate.deploy: 1
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: supernova
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
