version: '3'
services:
  backend:
    image: 145070974046.dkr.ecr.us-east-1.amazonaws.com/myinsdocker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - '3000:3000'
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: supernova
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
